### ISSUE TITLE
Can some of the slides be .md files?

### ISSUE THREAD

**Issue by wslack** [18F/slides#24]
re: https://github.com/18F/slides/commit/93a8d83ac98ab5095383a429532f77dd51ea0c92

It's easier to edit/view the file on GitHub as an .md file and I didn't lose any functionality as .MD; can I change it back?

cc @mbland

**Comment by mbland** [comment]
I don't _think_ so. The problem from #22 and #23 was that Jekyll will try to parse _all_ of the Markdown inside the `.md` file, including the Markdown for the slides themselves, which breaks the slides functionality. If anyone has an idea how to get around that, feel free to reopen the issue.
